export const complaints = [
  {
    id: "TKT-164568",
    name: "John Doe",
    email: "john@example.com",
    category: "Road Infrastructure",
    phone: "+250 788 123 456",
    address: "Kigali, Rwanda",
    message: "There are large potholes on Main Street causing accidents.",
    submittedAt: "2025-05-17",
    location: "Kigali, Rwanda",
    image: "https://example.com/image1.jpg",
    status: "Pending",
    response: null,
  },
  {
    id: "TKT-164569",
    name: "Jane Smith",
    email: "jane@example.com",
    category: "Public Utilities",
    phone: "+250 788 987 654",
    address: "Gasabo, Kigali, Rwanda",
    message: "Water outage in our neighborhood for two days.",
    submittedAt: "2025-05-15",
    location: "Gasabo, Kigali, Rwanda",
    image: "https://example.com/image2.jpg",
    status: "Resolved",
    response: "The water outage was due to a burst pipe, which has been repaired. Water supply was restored on 2025-05-16. Please contact us if issues persist.",
  }
];