// app/dashboard/data.ts
export const complaints = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    category: "Road Infrastructure",
    message: "There are large potholes on Main Street causing accidents.",
    submittedAt: "2025-05-17",
    status: "Pending",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    category: "Water Supply",
    message: "No running water in my area for 3 days now.",
    submittedAt: "2025-05-16",
    status: "In Progress",
  },
  {
    id: "3",
    name: "Ali Niyonzima",
    email: "ali@example.com",
    category: "Electricity",
    message: "Frequent power outages every evening in Kimironko.",
    submittedAt: "2025-05-15",
    status: "Resolved",
  },
  {
    id: "4",
    name: "Chantal Uwimana",
    email: "chantal@example.com",
    category: "Public Transport",
    message: "Bus service delays every morning at Nyabugogo.",
    submittedAt: "2025-05-14",
    status: "Pending",
  },
  {
    id: "5",
    name: "Eric Mugabo",
    email: "eric@example.com",
    category: "Waste Management",
    message: "Garbage hasn’t been collected for over a week.",
    submittedAt: "2025-05-13",
    status: "In Progress",
  },
  {
    id: "6",
    name: "Grace Uwera",
    email: "grace@example.com",
    category: "Healthcare",
    message: "Lack of doctors at the local health center.",
    submittedAt: "2025-05-12",
    status: "Pending",
  },
  {
    id: "7",
    name: "Samuel Habimana",
    email: "samuel@example.com",
    category: "Road Infrastructure",
    message: "Streetlights are not functioning at night.",
    submittedAt: "2025-05-11",
    status: "Resolved",
  },
  {
    id: "8",
    name: "Ines Mukamana",
    email: "ines@example.com",
    category: "Security",
    message: "There have been several thefts reported recently.",
    submittedAt: "2025-05-10",
    status: "Pending",
  },
  {
    id: "9",
    name: "Didier Ndoli",
    email: "didier@example.com",
    category: "Water Supply",
    message: "Contaminated water coming from the tap.",
    submittedAt: "2025-05-09",
    status: "In Progress",
  },
  {
    id: "10",
    name: "Marie Mukase",
    email: "marie@example.com",
    category: "Electricity",
    message: "Transformer near our house is making loud noises.",
    submittedAt: "2025-05-08",
    status: "Pending",
  },
  {
    id: "11",
    name: "Claude Tuyishime",
    email: "claude@example.com",
    category: "Public Transport",
    message: "Some drivers refuse to follow the route.",
    submittedAt: "2025-05-07",
    status: "Resolved",
  },
  {
    id: "12",
    name: "Aline Uwase",
    email: "aline@example.com",
    category: "Waste Management",
    message: "Public bins in the market are overflowing.",
    submittedAt: "2025-05-06",
    status: "In Progress",
  },
  {
    id: "13",
    name: "Patrick Nsabimana",
    email: "patrick@example.com",
    category: "Security",
    message: "No police patrols in our neighborhood lately.",
    submittedAt: "2025-05-05",
    status: "Pending",
  },
  {
    id: "14",
    name: "Rachel Ingabire",
    email: "rachel@example.com",
    category: "Healthcare",
    message: "Pharmacy at the hospital is always out of stock.",
    submittedAt: "2025-05-04",
    status: "Resolved",
  },
  {
    id: "15",
    name: "Kevin Karangwa",
    email: "kevin@example.com",
    category: "Road Infrastructure",
    message: "Unfinished road construction for 2 months.",
    submittedAt: "2025-05-03",
    status: "In Progress",
  },
  {
    id: "16",
    name: "Sylvie Nyirahabimana",
    email: "sylvie@example.com",
    category: "Electricity",
    message: "Power line is hanging dangerously near the road.",
    submittedAt: "2025-05-02",
    status: "Pending",
  },
  {
    id: "17",
    name: "Jean Bosco",
    email: "bosco@example.com",
    category: "Public Transport",
    message: "Bus stop shelter is damaged.",
    submittedAt: "2025-05-01",
    status: "Resolved",
  },
  {
    id: "18",
    name: "Laura Mutoni",
    email: "laura@example.com",
    category: "Water Supply",
    message: "Water pressure is very low in the mornings.",
    submittedAt: "2025-04-30",
    status: "Pending",
  },
  {
    id: "19",
    name: "Emmanuel Rugamba",
    email: "emmanuel@example.com",
    category: "Waste Management",
    message: "Illegal dumping near the playground.",
    submittedAt: "2025-04-29",
    status: "In Progress",
  },
  {
    id: "20",
    name: "Gloria Ishimwe",
    email: "gloria@example.com",
    category: "Security",
    message: "Broken street cameras not yet repaired.",
    submittedAt: "2025-04-28",
    status: "Pending",
  },
];
